# f = open("temp.txt","r")
# f1 = open("temp1.txt","a")
# count = 1
# for x in f:
# 	for i in range(5):
# 		index = x.find(str(count-i))
# 		if index != -1:
# 			break
# 	count += 1
# 	l1 = ""
# 	for i in range(index):
# 		l1 += x[i]
# 	f1.write(l1[:-1]+"\n")

f = open("temp1.txt","r")
count = 0
l = []
for x in f:
	if count%2 == 0:
		temp = x[:-1]
		temp = temp.title()
		l.append(temp+" mobile")
	count += 1
print(l)

# 5. Add device type
l = ['HP Laptop',
     'Asus Laptop',
     'MSI Laptop',
     'Apple Laptop',
     'Acer Laptop',
     'Dell Laptop',
     'Lenovo Laptop',
     'Microsoft Laptop',
     'Huawei Laptop',
     'Xiaomi Laptop',
     'Samsung Laptop',
     'Micromax Laptop',
     'HCL Laptop',
     'WIPRO Laptop',
     'Reliance Laptop',
     'LG Laptop',
     'Lava Laptop',
     'Sony Laptop',
     'Gateway Laptop',
     'NOTION INK Laptop',
     'Smartron Laptop',
     'Iball Laptop',
     'Toshiba Laptop',
     'Fujitsu Laptop',
     'Acer Mobile',
     'Alcatel Mobile',
     'Allview Mobile',
     'Amazon Mobile',
     'Amoi Mobile',
     'Apple Mobile',
     'AT&T Mobile',
     'Benefon Mobile',
     'Benq Mobile',
     'Benq-Siemens Mobile',
     'Bird Mobile',
     'Blackberry Mobile',
     'BLU Mobile',
     'Bosch Mobile',
     'BQ Mobile',
     'Casio Mobile',
     'CAT Mobile',
     'Celkon Mobile',
     'Chea Mobile',
     'Coolpad Mobile',
     'Dell Mobile',
     'Emporia Mobile',
     'Energizer Mobile',
     'Ericsson Mobile',
     'Eten Mobile',
     'Fairphone Mobile',
     'Fujitsu Siemens Mobile',
     'Garmin-Asus Mobile',
     'Gigabyte mobile',
     'Gionee mobile',
     'Google mobile',
     'Haier mobile',
     'Honor mobile', 
     'HP mobile',
     'HTC mobile',
     'Huawei mobile',
     'I-Mate mobile',
     'I-Mobile mobile',
     'Icemobile mobile',
     'Infinix mobile',
     'Innostream mobile',
     'Inq mobile',
     'Intex mobile',
     'Jolla mobile', 
     'Karbonn mobile', 
     'Kyocera mobile', 
     'Lava mobile',
     'Leeco mobile',
     'Lenovo mobile',
     'Lg mobile',
     'Maxon mobile',
     'Maxwest mobile',
     'Meizu mobile',
     'Micromax mobile',
     'Microsoft mobile',
     'Mitac mobile',
     'Mitsubishi mobile',
     'Modu mobile',
     'Motorola mobile',
     'Mwg mobile',
     'Nec mobile',
     'Neonode mobile',
     'Niu mobile',
     'Nokia mobile',
     'Nvidia mobile',
     'O2 mobile',
     'Oneplus mobile',
     'Oppo mobile',
     'Orange mobile',
     'Palm mobile',
     'Panasonic mobile',
     'Pantech mobile',
     'Parla mobile',
     'Philips mobile',
     'Plum mobile',
     'Posh mobile',
     'Prestigio mobile',
     'Qmobile mobile',
     'Qtek mobile',
     'Razer mobile',
     'Realme mobile',
     'Sagem mobile',
     'Samsung mobile',
     'Sendo mobile',
     'Sewon mobile',
     'Sharp mobile',
     'Siemens mobile',
     'Sonim mobile',
     'Sony mobile',
     'Sony Ericsson mobile',
     'Spice mobile',
     'T-Mobile mobile',
     'Tcl mobile',
     'Tecno mobile',
     'Tel.Me. mobile',
     'Telit mobile',
     'Thuraya mobile',
     'Toshiba mobile',
     'Ulefone mobile',
     'Unnecto mobile',
     'Vertu mobile',
     'Verykool mobile',
     'Vivo mobile',
     'Vk Mobile mobile',
     'Vodafone mobile',
     'Wiko mobile',
     'Wnd mobile',
     'Xcute mobile',
     'Xiaomi mobile',
     'Xolo mobile',
     'Yezz mobile',
     'Yota mobile',
     'Yu mobile',
     'Zte Device mobile'
     ]